{
 "title": "${DASHBOARD_TITLE}",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "organization", "label": "Organization", "query": "TS.QUERYINDEX qualifier=total" },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total{organizationId=\"$organization\"},workspaceId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Licensing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\n    FROM argo_archived_workflows\nWHERE phase = 'Failed'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\n    FROM argo_archived_workflows\nWHERE phase = 'Error'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(phase)\n    FROM argo_archived_workflows\nWHERE phase = 'Succeeded'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, instance) (argo_workflows_count{namespace=\"wa-adx-dev\", status=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, instance) (argo_workflows_count{namespace=\"wa-adx-dev\", status=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "eval \"return #redis.call('keys', 'ts2:metric:cosmotech:API:*:call')\" 0",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Total runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\n    FROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()"
    }
   ]
  },
  {
   "title": "Run started per day with status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT phase, count(*)\n    FROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()\ngroup by phase"
    }
   ]
  },
  {
   "title": "Run started per day",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*),  date_trunc('day',startedat)\n    FROM argo_archived_workflows\nWHERE ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/organizationId' = '$organization'\nAND ((workflow->>'metadata')::jsonb->>'labels')::jsonb->>'cosmotech.com/workspaceId' = '$workspace'\nAND startedat > $__timeFrom() and finishedat < $__timeTo()\ngroup by date_trunc('day',startedat)"
    }
   ]
  }
 ]
}