{
 "title": "${title}",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "organization", "label": "Organization", "query": "TS.QUERYINDEX qualifier=total" },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total{organizationId=~\"$organization\"}, workspaceId)"
    }
   },
   {
    "name": "userquery",
    "label": "Users",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total{organizationId=~\"$organization\", workspaceId=~\"$workspace\"}, user)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Users Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total distinct users",
   "type": "stat",
   "description": "Count of unique users, eliminating duplicates",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "cosmotech_findAllScenarios_total{user=~\"$userquery\", organizationId=~\"$organization\", workspaceId=~\"$workspace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily user sign in",
   "type": "timeseries",
   "description": "Daily count of user sign-ins via the web app",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by(time) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$userquery\", organizationId=~\"$organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Users sign in",
   "type": "stat",
   "description": "Inclusive count of unique user sign-ins",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (time) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$userquery\", organizationId=~\"$organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sign in per User",
   "type": "piechart",
   "description": "Cumulative sign-ins via web app + scenarios deletion per user over time",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$userquery\", organizationId=~\"$organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Daily sign in per User",
   "type": "timeseries",
   "description": "Evolution of distinct user sign-ins via web app over time",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$userquery\", organizationId=~\"$organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Run Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total count of runner runs",
   "type": "stat",
   "description": "Aggregate count of unique runner runs",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "ts.mrange",
     "filter": "service=run name=run:$organization:$workspace downsampling=true",
     "keyName": "ts2:metric:cosmotech:run:run:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Daily Runner Run ",
   "type": "timeseries",
   "description": "Cumulative daily count of runner executions",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 24 },
   "targets": [
    {
     "aggregation": "max",
     "bucket": 86400000,
     "command": "ts.mrange",
     "filter": "service=run name=run:$organization:$workspace downsampling=true",
     "keyName": "ts2:metric:cosmotech:run:run:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Maximum of parallel runner run on period  (No filters)",
   "type": "stat",
   "description": "Peak simultaneous runner runs, no filters except time range",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucket": 31536000000,
     "command": "ts.mrange",
     "filter": "service=run name=running:$organization:$workspace downsampling=true",
     "keyName": "service=run name=run:$organization:$workspace downsampling=true",
     "type": "timeSeries"
    }
   ]
  },
  { "title": "Scenario Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total count of scenario runs",
   "type": "stat",
   "description": "Aggregate count of unique scenario runs",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "ts.mrange",
     "filter": "service=scenariorun name=run:$organization:$workspace downsampling=true",
     "keyName": "ts2:metric:cosmotech:scenariorun:run:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Daily Scenarios Run ",
   "type": "timeseries",
   "description": "Cumulative daily count of scenario executions",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "targets": [
    {
     "aggregation": "max",
     "bucket": 86400000,
     "command": "ts.mrange",
     "filter": "service=scenariorun name=run:$organization:$workspace downsampling=true",
     "keyName": "ts2:metric:cosmotech:scenariorun:run:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Maximum of parallel scenario run on period  (No filters)",
   "type": "stat",
   "description": "Peak simultaneous scenario runs, no filters except time range",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucket": 31536000000,
     "command": "ts.mrange",
     "filter": "service=scenariorun name=running:$organization:$workspace downsampling=true",
     "keyName": "ts2:metric:cosmotech:scenariorun:running:total:ds",
     "type": "timeSeries"
    }
   ]
  }
 ]
}