{
 "title": "${title}",
 "time": { "from": "now-30d", "to": "now-1d" },
 "refresh": "5m",
 "panels": [
  { "title": "Connected Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total User Count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1h])) > 0) or vector(0)",
     "legendFormat": "Users count"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1d])) > 0) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current Users Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1m])) > 0) or vector(0)",
     "legendFormat": "Users count"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1m])) > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1d])) > 0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1m])) > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1d])) > 0) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (sum by (user) (increase({__name__=~\"cosmo.*\"}[1m])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Users actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Users Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmo.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 2, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmo.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Users Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Api Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Api Request Count",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1d]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1d]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Current Api Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Current Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1d]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1d]))",
     "legendFormat": "Request Count"
    }
   ]
  },
  {
   "title": "Max user",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"cosmo.*\"}[1m]))",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}