replicaCount: 1

nameOverride: ""
fullnameOverride: ""

cosmotech-api:
  version: ${COSMOTECH_API_VERSION}

image:
  repository: ghcr.io/cosmo-tech/cosmotech-copilot-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082
  targetPort: http

ingress:
  enabled: true
  host: ${COSMOTECH_API_DNS_NAME}
  name: cosmotech-copilot-api
  serviceName: cosmotech-copilot-api
  tlsSecretName: ${TLS_SECRET_NAME}
  certManagerClusterIssuer: ${TLS_SECRET_NAME}
  email: platform@cosmotech.com
  appPath: ${APP_PATH}

envConfig:
  modeSettings:
    MODE: ${MODE}
    PORT: ${PORT}
    AI_PROVIDER: ${AI_PROVIDER}
  adxSettings:
    AAD_TENANT_ID: ${AAD_TENANT_ID}
    KUSTO_CLUSTER_URL: ${KUSTO_CLUSTER_URL}
    KUSTO_DATABASE: ${KUSTO_DATABASE}
    ADX_AAD_APP_ID: ${ADX_AAD_APP_ID}
    ADX_AAD_SECRET: ${ADX_AAD_SECRET}
    ADX_RETRIEVED_ROW_NB: ${ADX_RETRIEVED_ROW_NB}
  vectorStore:
    IS_VECTOR_STORE_LOCAL: ${IS_VECTOR_STORE_LOCAL}
    CONTEXT_FILE_PATH: ${CONTEXT_FILE_PATH}
  searchSettings:
    SEARCH_ENDPOINT_URL: ${SEARCH_ENDPOINT_URL}
    SEARCH_API_KEY: ${SEARCH_API_KEY}
    INDEX_NAME: ${INDEX_NAME}
    RETRIEVED_DOCUMENT_NB: ${RETRIEVED_DOCUMENT_NB}
    CHUNK_SIZE: ${CHUNK_SIZE}
    CHUNK_OVERLAP: ${CHUNK_OVERLAP}
  openAiSettings:
    AZURE_OPEN_AI_ENDPOINT: ${AZURE_OPEN_AI_ENDPOINT}
    AZURE_OPEN_AI_API_KEY: ${AZURE_OPEN_AI_API_KEY}
    AZURE_OPEN_AI_API_TYPE: ${AZURE_OPEN_AI_API_TYPE}
    AZURE_OPEN_AI_API_VERSION: ${AZURE_OPEN_AI_API_VERSION}
    LLM_DEPLOYMENT_NAME: ${LLM_DEPLOYMENT_NAME}
    EMBEDDINGS_DEPLOYEMENT_NAME: ${EMBEDDINGS_DEPLOYEMENT_NAME}
    TEMPERATURE: ${TEMPERATURE}
    MAX_TOKEN: ${MAX_TOKEN}
    STREAMING: ${STREAMING}
  botSettings:
    AZURE_BOT_APP_ID: ${AZURE_BOT_APP_ID}
    AZURE_BOT_PASSWORD: ${AZURE_BOT_PASSWORD}
    AZURE_BOT_DIRECTLINE_SECRET: ${AZURE_BOT_DIRECTLINE_SECRET}
  cosmotechApi:
    COMOSTECH_API_HOST: ${COMOSTECH_API_HOST}
    COSMOTECH_API_SCOPE: ${COSMOTECH_API_SCOPE}
    COMOSTECH_API_TENANT_ID: ${COMOSTECH_API_TENANT_ID}
    COSMOTECH_API_CLIENT_ID: ${COSMOTECH_API_CLIENT_ID}
    COSMOTECH_API_CLIENT_SECRET: ${COSMOTECH_API_CLIENT_SECRET}
    ORGANIZATION: ${ORGANIZATION}
    WORKSPACE: ${WORKSPACE}
