#!/bin/bash

# Fonction pour exécuter des commandes Vault
vault_cmd() {
  kubectl -n $VAULT_NAMESPACE exec -i vault-0 -- vault "$@"
}

vault_cmd kv put -mount=${vault_engine_secret} ${tenant_id}/${cluster_name}/${NAMESPACE}-platform-secrets API_VERSION=${API_VERSION} \
  ACR_SERVER=${ACR_SERVER} \
  ACR_USERNAME=${ACR_USERNAME} \
  ACR_PASSWORD=${ACR_PASSWORD} \
  ACR_REGISTRY_URL=${ACR_REGISTRY_URL} \
  HOST_COSMOTECH_API=${HOST_COSMOTECH_API} \
  IDENTITY_AUTHORIZATION_URL=${IDENTITY_AUTHORIZATION_URL} \
  IDENTITY_TOKEN_URL=${IDENTITY_TOKEN_URL} \
  MONITORING_NAMESPACE=${MONITORING_NAMESPACE} \
  NAMESPACE=${NAMESPACE} \
  ARGO_SERVICE_ACCOUNT_NAME=${ARGO_SERVICE_ACCOUNT_NAME} \
  AZURE_TENANT_ID=${AZURE_TENANT_ID} \
  AZURE_APPID_URI=${AZURE_APPID_URI} \
  AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY} \
  AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME} \
  AZURE_CREDENTIALS_CLIENT_ID=${AZURE_CREDENTIALS_CLIENT_ID} \
  AZURE_CREDENTIALS_CLIENT_SECRET=${AZURE_CREDENTIALS_CLIENT_SECRET} \
  AZURE_CREDENTIALS_CUSTOMER_CLIENT_ID=${AZURE_CREDENTIALS_CUSTOMER_CLIENT_ID} \
  AZURE_CREDENTIALS_CUSTOMER_CLIENT_SECRET=${AZURE_CREDENTIALS_CUSTOMER_CLIENT_SECRET} \
  ADX_BASE_URI=${ADX_BASE_URI} \
  ADX_INGEST_URI=${ADX_INGEST_URI} \
  EVENTBUS_BASEURI=${EVENTBUS_BASEURI} \
  HOST_POSTGRES=${HOST_POSTGRES} \
  HOST_REDIS=${HOST_REDIS} \
  HOST_REDIS_PASSWORD=${HOST_REDIS_PASSWORD} \
  HOST_ARGO_WORKFLOWS_SERVER=${HOST_ARGO_WORKFLOWS_SERVER} \
  RDS_HUB_LISTENER=${RDS_HUB_LISTENER} \
  RDS_HUB_SENDER=${RDS_HUB_SENDER} \
  RDS_STORAGE_ADMIN=${RDS_STORAGE_ADMIN} \
  RDS_STORAGE_READER=${RDS_STORAGE_READER} \
  RDS_STORAGE_WRITER=${RDS_STORAGE_WRITER} \
  HOST_RDS=${HOST_RDS} \
  HOST_RDS_POSTGRES=${HOST_RDS_POSTGRES} \
  SPRING_APPLICATION_JSON="{ \"csm\":{ \"platform\":{ \"identityProvider\":{ \"defaultScopes\":{ \"[${AZURE_APPID_URI}/platform]\":\"${NAMESPACE} scope\" }, \"containerScopes\":{ \"[${AZURE_APPID_URI}/.default]\":\"${NAMESPACE} scope\" }}}}}"