auth:
  password: ${REDIS_PASSWORD}
serviceBindings: 
  enabled: true
image:
  registry: ghcr.io
  repository: cosmo-tech/cosmotech-redis
  tag: ${VERSION_REDIS_COSMOTECH}
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: latest
    pullPolicy: IfNotPresent
sysctl:
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: latest
    pullPolicy: IfNotPresent
master:
  podSecurityContext:
    enabled: true
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  persistence:
    enabled: true
    size: ${REDIS_DISK_SIZE}
    storageClass: ${REDIS_MASTER_STORAGE_CLASS_NAME}
    existingClaim: ${REDIS_MASTER_EXISTING_PVC_NAME}
  podLabels:
    networking/traffic-allowed: "yes"
  tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"
  nodeSelector:
    cosmotech.com/tier: "db"
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 4Gi
replica:
  podSecurityContext:
    enabled: true
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  replicaCount: 1
  podLabels:
    networking/traffic-allowed: "yes"
  persistence:
    enabled: true
    size: ${REDIS_DISK_SIZE}
    storageClass: ${REDIS_REPLICA_STORAGE_CLASS_NAME}
    existingClaim: ${REDIS_REPLICA_EXISTING_PVC_NAME}
  tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"
  nodeSelector:
    "cosmotech.com/tier": "db"
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 4Gi
commonConfiguration: |-
  loadmodule /opt/bitnami/redis/modules/redisgraph.so
  loadmodule /opt/bitnami/redis/modules/redistimeseries.so DUPLICATE_POLICY LAST
  loadmodule /opt/bitnami/redis/modules/rejson.so
  loadmodule /opt/bitnami/redis/modules/redisearch.so
