name: Track Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  dependency_track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Install terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - name: create terraform.lock.hcl
        run: |
          terraform init
      - name: Install Syft
        run: |
          curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: |
          syft scan -o cyclonedx-json . > sbom.json
      - name: Upload cyclonedx bom to dependency
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ secrets.DEPENDENCY_TRACK_SERVER_HOSTNAME }}
          apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project: '50ecafaf-a3ec-4f0d-a7a9-0e7e949395f0'
          bomfilename: 'sbom.json'
