name: Track Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [edited]


jobs:
  dependency_track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'sbom.json'
      - name: Upload cyclonedx bom to dependency
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ secrets.DEPENDENCY_TRACK_SERVER_HOSTNAME }}
          apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project: '50ecafaf-a3ec-4f0d-a7a9-0e7e949395f0'
          bomfilename: 'sbom.json'